### Get / route    
GET  http://localhost:3000/
Content-Type: application/json

### Get users
GET http://localhost:3000/users
Content-Type: application/json

### Post new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "PETIKE", 
    "email": "123@gmail.com", 
    "password": "123"
}

### Get user by ID
GET  http://localhost:3000/users/1
Content-Type: application/json

### Login user
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "ember@gmail.com",
    "password": "123"
}

### adat törtlés id alapján
DELETE  http://localhost:3000/users/2
Content-Type: application/json

### Email,név módosítás
PATCH  http://localhost:3000/users/profile/2
Content-Type: application/json

{
    "name":"peti",
    "email":"123@gmail.com"
}

### Jelszó változtatása
PATCH  http://localhost:3000/users/password/2
Content-Type: application/json

{
    "oldpass": "1234",
    "newpass": "123"
}